export const text = {
	monday: "Понедельник",
	tuesday: "Вторник",
	wednesday: "Среда",
	thursday: "Четверг",
	friday: "Пятница",
	saturday: "Суббота",
	sunday: "Воскресенье",
	avg_formative: "Среднее формативов: ",
	avg_summative: "Среднее саммативов: ",
	avg_final: "Среднее итоговых: ",
	bronze: "Бронзовые",
	silver: "Серебряные",
	golden: "Золотые",
	enter_username: "Вы не ввели имя пользователя!",
	enter_username_2: "Введите своё школьное имя пользователя.",
	enter_password: "Вы не ввели пароль!",
	enter_password_2: "Введите свой школьный пароль.",
	error: "Ошибка",
	err_schedule: "Расписание",
	err_plan: "Учебный план",
	err_hw_this: "Д/з на эту неделю",
	err_hw_next: "Д/з на следующую неделю",
	err_marks: "Оценки",
	err_diploma_sport: "Диплом: Спорт и здоровье",
	err_diploma_creativity: "Диплом: Творчество и изобретательство",
	err_diploma_responsibility:
		"Диплом: Социальная и гражданская ответственность",
	err_diploma_science: "Диплом: Наука и познание",
	err_diploma_leadership: "Диплом: Лидерство и взаимодействие",
	err_olympiads: "Олимпиады",
	login_success: "Успех!",
	login_success_2: "Вы успешно вошли в свой аккаунт.",
	login_fail: "Неверный логин/пароль!",
	login_fail_2: "Пожалуйста, введите правильные логин и пароль.",
	uname: "Имя пользователя",
	pwd: "Пароль",
	log_in: "Войти",
	logging_in: "Входим...",
	log_out: "Выйти",
	log_out_info:
		"Если вы выйдете, то ваши логин и пароль будут удалены с устройства, и вы не сможете входить автоматически. Также вы не сможете получать уведомления.",
	this_week: "Эта неделя",
	next_week: "Следующая неделя",
	made_by: "Сделано с ❤️ Milk_Cool (Миланом) и Leaftail (Андреем)",
	link: "Ссылка",
	no_link: "Ссылки нет",
	s_log_out: "Выход",
	s_log_in: "Вход",
	s_schedule: "Расписание",
	s_marks: "Оценки",
	s_homework: "Домашка",
	s_other: "Другое",
	s_other_options: "Другие опции",
	s_groups: "Группы",
	s_diploma: "Диплом Летово",
	s_olympiads: "Олимпиады",
	s_settings: "Настройки",
	s_info: "Информация",
	language: "Язык",
	diploma_sport: "Спорт и здоровье",
	diploma_creativity: "Творчество и изобретательство",
	diploma_responsibility: "Социальная и гражданская ответственность",
	diploma_science: "Наука и познание",
	diploma_leadership: "Лидерство и взаимодействие",
	notification_error_physical:
		"Нужно использовать настоящее устройство, чтобы получать уведомления.",
	notification_error_token: "Не получилось получить токен для уведомлений!",
	notification: "Уведомления",
	notification_disable: "Выключить уведомления",
	notification_enable: "Включить уведомления",
};

Date.prototype.getDayMon = function () {
	return [6, 0, 1, 2, 3, 4, 5][this.getDay()];
};
